sudo: false
language: scala
install:
  - npm install jsdom
#before_deploy:
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  target-branch: gh-pages
#  local-dir:
#  on:
#    branch: poc-cappio