# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
sudo: false
language: scala
jdk: oraclejdk8
install:
- npm install jsdom
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete


script:
- sbt ++$TRAVIS_SCALA_VERSION test

after_success:
- mkdir deploy
- cp ./ui/index.html deploy
- cp ./ui/target/scala-2.12/ui-opt.js deploy
- cp ./ui/target/scala-2.12/ui-jsdeps.js deploy
before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: deploy
  on:
    branch: poc-cappio
after_deploy:
- rm -rf deploy